/// <reference types="jest" />
import { afterAll,beforeAll,beforeEach,describe,expect,it,jest } from '@jest/globals';
import crypto from 'crypto'; import mongoose from 'mongoose'; import request from 'supertest'; import { MongoMemoryServer } from 'mongodb-memory-server'; import app from '../app'; import { User,CareerPath } from '../models'; import { Game } from '../models/Game';
jest.setTimeout(30000); let mongo:MongoMemoryServer|undefined; let password='';
beforeAll(async()=>{mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());},30000);afterAll(async()=>{if(mongoose.connection.readyState)await mongoose.disconnect();if(mongo)await mongo.stop();});beforeEach(async()=>{await Promise.all([User.deleteMany({}),CareerPath.deleteMany({}),Game.deleteMany({})]);password=crypto.randomBytes(18).toString('base64url')+'Aa1!';});
async function session(){const user=await User.create({name:'Upload Test',email:'upload@example.invalid',password,isEmailVerified:true});const agent=request.agent(app);const login=await agent.post('/api/auth/login').send({email:user.email,password});return{user,agent,csrf:login.body.csrfToken};}
describe('upload lifecycle and ownership',()=>{
 it('rejects unsupported files before processing',async()=>{const{agent,csrf}=await session();const res=await agent.post('/api/games/from-pdf').set('X-CSRF-Token',csrf).attach('pdf',Buffer.from('plain text'),'notes.txt');expect(res.status).toBe(400);expect(res.body.message).toMatch(/PDF/);});
 it('deletes only an owned quiz',async()=>{const{user,agent,csrf}=await session();const own=await Game.create({userId:user._id,title:'Owned',sourceType:'text',questions:[],totalQuestions:0});expect((await agent.delete(`/api/games/${own._id}`).set('X-CSRF-Token',csrf)).status).toBe(200);const other=await User.create({name:'Other',email:'other@example.invalid',password:crypto.randomBytes(18).toString('base64url')+'Aa1!',isEmailVerified:true});const theirs=await Game.create({userId:other._id,title:'Other',sourceType:'text',questions:[],totalQuestions:0});expect((await agent.delete(`/api/games/${theirs._id}`).set('X-CSRF-Token',csrf)).status).toBe(404);});
 it('deletes only an owned career path',async()=>{const{user,agent,csrf}=await session();const path=await CareerPath.create({userId:user._id,dreamJob:'Engineer',company:'Example',requiredSkills:[],industryExpectations:[],interviewTopics:[],techStack:[]});expect((await agent.delete(`/api/career/paths/${path._id}`).set('X-CSRF-Token',csrf)).status).toBe(200);expect(await CareerPath.findById(path._id)).toBeNull();});
});
